# INFLUENCE OF NEIGHBORHOOD INTERACTIONS ACROSS SPECIES RANGES

### 1. HOW DOES THE EFFECT OF NCI ON G/S VARY FOR INDIVIDUAL SP ACROSS THE PLOTS?
### 2. HOW DOES THIS VARIATION RELATE TO THEIR OVERALL DISTRIBUTIONS ACROSS THE GRADIENT?
# DOES THE STRENGTH OF NEIGHBORHOOD INTERACTIONS VARY PREDICTABLY WITH CLIMATE?
# DOES THE STRENGHT OF NEIGHBORHOOD INTERACTIONS VARY WITH POSITION IN RANGE?
# DOES THE STRENGTH OF NEIGHBORHOOD INTERACTIONS REMAIN CONSISTENT ACROSS THE RANGE?
### 3. DO TRAITS EXPLAIN THE DEGREE TO WHICH SENSITIVITY TO CROWDING CHANGES ALONG THE GRADIENT?
### 4. DOES THE RELATIVE EFFECT OF CROWDING IN DIFFERENT SIZE CLASSES VARY ACROSS PLOTS?

# IDENTIFY SHARED SPECIES ACROSS PANAMA PLOTS
x <- table(tdata$spcode, tdata$plot)>0
sum(rowSums(x)==2) # 164 species shared in 2 plots
sum(rowSums(x[,c(1,2)])==2) # bci x coc share 114 species
sum(rowSums(x[,c(1,3)])==2) # bci x she share 136 species
sum(rowSums(x[,c(2,3)])==2) # coc x she share 55 species
sum(rowSums(x)==3) # 47 species shared across all 3 plots

rownames(x)[rowSums(x)==3]
tmp <- tdata[tdata$spcode %in% rownames(x)[rowSums(x)==3],]
tmp <- droplevels(tmp)
table(tmp$spcode, tmp$plot)


# THESE DATA COULD BE SUPPLEMENTED WITH THE SMALL PLOT DATA...


